apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: hacbs-test-project-ukh8
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: hacbs-test-project-ukh8
    app.kubernetes.io/part-of: rhtap-demo-app
  name: hacbs-test-project-ukh8
spec:
  replicas: 1
  revisionHistoryLimit: 0
  selector:
    matchLabels:
      app: hacbs-jvm-build-test-project
      app.kubernetes.io/instance: hacbs-test-project-ukh8
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: hacbs-jvm-build-test-project
        app.kubernetes.io/instance: hacbs-test-project-ukh8
    spec:
      containers:
      - image: quay.io/redhat-appstudio-qe/rhtap-demo-uoyo-tenant/rhtap-demo-app/hacbs-test-project-ukh8@sha256:7230944402ff70235240b36b44b86ae9704bed138ca873292f4725fa01af1709
        name: hacbs-jvm-build-test-project
        ports:
        - containerPort: 8081
          name: http
          protocol: TCP
        resources:
          limits:
            cpu: 500m
            memory: 1Gi
status: {}
