apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  name: hacbs-test-project-ukh8
spec:
  selector: {}
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
    spec:
      containers:
      - image: quay.io/redhat-appstudio-qe/rhtap-demo-uoyo-tenant/rhtap-demo-app/hacbs-test-project-ukh8@sha256:cde8011e66d0329f5db0fe3a84508c50d8419037886e9ddf7bfbf08fdc1e0d84
        name: hacbs-jvm-build-test-project
        resources: {}
status: {}
